package constant;

public class QueryConstants {

	public static final String DELETE = "DELETE FROM";
	public static final String INSERT = "INSERT INTO ";
	public static final String STD_ETL_DIM_AREA_ORIENTADORA = "MOU.TB_EXT_DIM_AREA_ORIENTADORA (CD_AREA_ORIENTADORA,DS_AREA_ORIENTADORA) values (?,?)";
	public static final String STD_ETL_DIM_AREA_SOLUCIONADORA = "MOU.TB_EXT_DIM_AREA_SOLUCIONADORA (CD_AREA_SOLUCIONADORA,DS_AREA_SOLUCIONADORA) values (?,?)";
	public static final String STD_ETL_DIM_FAMILIA = "MOU.TB_EXT_DIM_FAMILIA (CD_FAMILIA,DS_FAMILIA) values (?,?)";
	public static final String STD_ETL_DIM_LOCAIS = "MOU.TB_EXT_DIM_LOCAIS (CD_LOCAL_PEOPLESOFT,CD_EMPRESA_LOCAL,CD_TIPO_LOCAL,DS_TIPO_LOCAL,CD_LOCAL,DS_LOCAL,DS_REGIONAL_LOCAL,DS_REDE_LOCAL) values (?,?,?,?,?,?,?,?)";
	public static final String STD_ETL_DIM_ODC = "MOU.TB_EXT_DIM_ODC (CD_ODC,DS_ODC) values (?,?)";
	public static final String STD_ETL_DIM_PRAZO_SLA = "MOU.TB_EXT_DIM_PRAZO_SLA (CD_TIPO_MANIFESTACAO,CD_CANAL_OCORRENCIA,CD_PRODUTO,CD_PROCESSO,CD_SINTOMA,CD_SEGMENTO_CLIENTE,PRAZO_SLA,PRAZO_CLIENTE,PRAZO_ANALISE) values (?,?,?,?,?,?,?,?,?)";
	public static final String STD_ETL_DIM_PRODUTO = "MOU.TB_EXT_DIM_PRODUTO (CD_PRODUTO,DS_PRODUTO) values (?,?)";
	public static final String STD_ETL_DIM_SINTOMA = "MOU.TB_EXT_DIM_SINTOMA (CD_PRODUTO,CD_PROCESSO,CD_SINTOMA,DS_SINTOMA_CURTO,DS_SINTOMA_LONGO,DS_SINTOMA_COMPLETO) values (?,?,?,?,?,?)";
	public static final String STD_ETL_DIM_SUPERVISOR = "MOU.TB_EXT_DIM_SUPERVISOR (CD_FCENAPE_SUPERVISOR,CD_FCENAPE_USUARIO,CD_CELULA_FILHO,CD_CELULA_MAE) values (?,?,?,?)";
	public static final String STD_ETL_DIM_TIPO_OBSERVACAO = "MOU.TB_EXT_DIM_TIPO_OBSERVACAO (CD_TIPO_OBSERVACAO,DS_TIPO_OBSERVACAO) values (?,?)";
	public static final String STD_ETL_DIM_USUARIO = "MOU.TB_EXT_DIM_USUARIO (CD_LOGIN_USUARIO,DS_USUARIO,CD_USUARIO) values (?,?,?)";
	public static final String STD_ETL_FATO_FINANCEIRA = "MOU.TB_EXT_FATO_FINANCEIRA (ID_MANIFESTACAO,CD_CONTRATO_FINANCEIRA,DS_TIPO_CONTRATO_FINANCEIRA) values (?,?,?)";
	public static final String STD_ETL_FATO_RL_MANIFESTACAO = "MOU.TB_EXT_FATO_RL_MANIFESTACAO (ID_MANIFESTACAO,ID_MANIFESTACAO_RELACIONADA,CD_TIPO_RELACIONAMENTO) values (?,?,?)";
	public static final String STD_ETL_FATO_ENDERECO_CLIENTE = "MOU.TB_EXT_FATO_ENDERECO_CLIENTE (ID_MANIFESTACAO,CD_PAIS,DS_ENDERECO,DS_CIDADE,DS_BAIRRO,CD_ESTADO,CD_CEP) values (?,?,?,?,?,?,?)";
	public static final String STD_ETL_FATO_CLIENTE = "MOU.TB_EXT_FATO_CLIENTE (ID_MANIFESTACAO,CD_TIPO_CLIENTE,CD_EMPRESA_CLIENTE,CD_CPF_CNPJ,CD_CLIC_DBM,CD_BANCO_CLIENTE,DS_NOME_CLIENTE,DS_GENERO_CLIENTE,DT_NASCIMENTO_CLIENTE,CD_AGENCIA_CLIENTE,CD_CONTA_CLIENTE,CD_BANCO_CONTA_CLIENTE,DT_ABERTURA_CONTA,DS_METODO_CONTATO_1,CD_CONTATO_1,DS_METODO_CONTATO_2,CD_CONTATO_2,CD_TIPO_LOCAL_VINCULO,CD_LOCAL_VINCULO,DS_LOCAL_VINCULO) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";
	public static final String STD_ETL_FATO_DESCRICAO = "MOU.TB_EXT_FATO_DESCRICAO (ID_MANIFESTACAO,DS_DESCRICAO_MANIFESTACAO) values (?,?)";
	public static final String STD_ETL_FATO_OBSERVACAO = "MOU.TB_EXT_FATO_OBSERVACAO (ID_MANIFESTACAO,CD_ORDEM_OBSERVACAO,CD_TIPO_OBSERVACAO,DS_VALOR_OBSERVACAO,DTTM_CRIACAO_OBSERVACAO,CD_ANALISTA_CRIACAO,DTTM_ALTERACAO_OBSERVACAO,CD_ANALISTA_ULTIMA_ALTERACAO,DS_DESCRICAO_OBSERVACAO) values (?,?,?,?,?,?,?,?,?)";
	public static final String STD_ETL_FATO_CANAL_CONTACTADO = "MOU.TB_EXT_FATO_CANAL_CONTACTADO (ID_MANIFESTACAO,CD_CANAL_CONTACTADO) values (?,?)";
	public static final String STD_ETL_FATO_MANIFESTACAO = "MOU.TB_EXT_FATO_MANIFESTACAO (ID_MANIFESTACAO,CD_EMPRESA,CD_TIPO_MANIFESTACAO,CD_STATUS_MANIFESTACAO,DTTM_CRIACAO_MANIFESTACAO,DTTM_ULTIMA_ALTERACAO,DTTM_REABERTURA,DTTM_FECHAMENTO_MANIFESTACAO,DTTM_PRAZO_SLA,DTTM_PRAZO_CLIENTE,CD_FAMILIA,CD_PRODUTO,CD_PROCESSO,CD_SINTOMA,CD_CANAL_ORIGEM,CD_EMPRESA_ALVO_MANIFESTACAO,CD_CANAL_OCORRENCIA,CD_SEGMENTO_CLIENTE,CD_EMPRESA_LOCAL_ORIGEM,CD_TIPO_LOCAL_ORIGEM,CD_LOCAL_ORIGEM,CD_ANALISTA_ABERTURA,CD_ANALISTA_ULTIMA_ALTERACAO,CD_ANALISTA_FECHAMENTO,CD_ANALISTA_RESPONSAVEL,CD_AREA_SOLUCIONADORA,CD_AREA_ORIENTADORA,IC_RESOLVIDO_PRIMEIRO_CONTATO,IC_REINCIDENCIA,IC_MANIFESTACAO_PROCEDENTE,IC_CLIENTE_ATENDIDO,CD_LOCAL_COBRANCA,CD_AGENCIA_RECLAMADA,CD_TIPO_ENVIO_COMPROVANTE,IC_CONTACTOU_OUTROS_CANAIS,DS_DESCRICAO_MANIFESTACAO,CD_TIPO_CARTAO,CD_NR_CARTAO,DS_SUBSEGMENTO,IC_PRAZO_SLA_URGENTE,IC_CRITICO,IC_ORGAO_REGULADOR,VLR_ESTORNO_SOLIC,VLR_ESTORNO_EFET,VLR_RESSARCIMENTO_SOLIC,VLR_RESSARCIMENTO_EFET,IC_POSITIVACAO,CD_MOTIVO_INSATISFACAO,DS_MOTIVO_INSATISFACAO,CD_USER_ENVOLVIDO) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public static final String STD_ETL_FATO_ODC = "MOU.TB_EXT_FATO_ODC (ID_MANIFESTACAO,DTTM_ULTIMA_ALTERACAO,IC_INTERROMPER_ESCALONAMENTO,CD_ODC,CD_PROCESSO_ODC,DT_OFICIO_ODC,DTTM_PRAZO_ODC,DT_ENCERRAMENTO_ODC,DS_STATUS_CONCLUSAO,IC_PRAZO_SLA_URGENTE,DTTM_AVISO_ODC) values (?,?,?,?,?,?,?,?,?,?,?)";
	public static final String STD_ETL_DIM_STATUS = "MOU.TB_EXT_DIM_STATUS (CD_STATUS_MANIFESTACAO,DS_STATUS_MANIFESTACAO) values (?,?)";
	public static final String STD_ETL_DIM_TIPO_MANIFESTACAO = "MOU.TB_EXT_DIM_TIPO_MANIFESTACAO (CD_TIPO_MANIFESTACAO,DS_TIPO_MANIFESTACAO) values (?,?)";
	public static final String STD_ETL_FATO_CONTADOR = "MOU.TB_EXT_FATO_CONTADOR(DS_DESCRICAO_CONTADOR,DTTM_ABERTURA_CONTADOR,CD_ANALISTA_ABERTURA_CONTADOR,CD_EMPRESA_CONTADOR) values (?,?,?,?)";
	public static final String STD_ETL_DIM_SEGMENTO_CLIENTE = "MOU.TB_EXT_DIM_SEGMENTO_CLIENTE (CD_SEGMENTO_CLIENTE,DS_SEGMENTO_CLIENTE) values (?,?)";
	public static final String STD_ETL_DIM_CANAL_OCORRENCIA = "MOU.TB_EXT_DIM_CANAL_OCORRENCIA (CD_CANAL_OCORRENCIA,DS_CANAL_OCORRENCIA) values (?,?)";
	public static final String STD_ETL_DIM_CANAL_ORIGEM = "MOU.TB_EXT_DIM_CANAL_ORIGEM (CD_CANAL_ORIGEM,DS_CANAL_ORIGEM,DS_LONGA_CANAL_ORIGEM) values (?,?,?)";
	public static final String STD_ETL_DIM_LOCAL_SOLUCAO = "MOU.TB_EXT_DIM_LOCAL_SOLUCAO (CD_LOCAL_SOLUCAO,DS_LOCAL_SOLUCAO) values (?,?)";
	public static final String REL_TRACKING = "MOU.TB_EXT_REL_TRACKING (ID_MANIFESTACAO,DS_AREA_SOLUCIONADORA,DTTM_PRAZO_SLA,DS_FASE,DS_EVENTO_TRACKING,DT_INICIO,DT_FIM,TM_HRS_UTEIS,DS_STATUS_SLA,DT_CRIACAO,DS_STATUS_MANIFESTACAO,ID_USUARIO,DS_USUARIO) values (?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public static final String INSER_QUERY = "UPDATE MOU.TB_QUERYS_ETL_OUVIDORIA SET QUERY=TO_CLOB('?') WHERE ID_QUERY=TO_NUMBER('?')";

}
